export const ADD_FAV = "ADD_FAV";
export const REMOVE_FAV = "REMOVE_FAV";
export const FILTER = "FILTER";
export const ORDER = "ORDER";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CHECK_CREDENTIALS_SUCCESS = "CHECK_CREDENTIALS_SUCCESS"; 
export const CHECK_CREDENTIALS_FAILURE = "CHECK_CREDENTIALS_FAILURE"; 
